import PageLayout from "@/components/page-layout";
import { Metadata } from "next";


export const metadata: Metadata = {
  title: "Page Auth",
  description: "Generated by create next app",
};

export default function PageAuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <PageLayout>
        {children}
      </PageLayout>
      
    </>
  );
}
