import { SidebarProvider } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import "react-toastify/dist/ReactToastify.css";

import { AppSidebar } from "@/components/dashboard/app-sidebar"
import {
  SidebarInset,
} from "@/components/ui/sidebar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <SidebarInset>
        {children}
      </SidebarInset>
    </SidebarProvider>
  );
}
