import { SidebarProvider } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import "react-toastify/dist/ReactToastify.css";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";

import { AppSidebar } from "@/components/dashboard/app-sidebar"
import {
  SidebarInset,
} from "@/components/ui/sidebar"
import { authOptions } from "@/lib/auth/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  if (!session) {
    redirect("/login");
  }

  return (
    <SidebarProvider>
      <AppSidebar />
      <SidebarInset>
        {children}
      </SidebarInset>
    </SidebarProvider>
  );
}
